### ISSUE TITLE
Decide on DAO Platform

### ISSUE THREAD

**Issue by mikepsinn** [cure-dao/docs#169]
- [A comparative analysis of the platforms for decentralized autonomous organizations in the Ethereum blockchain](https://jisajournal.springeropen.com/articles/10.1186/s13174-021-00139-6)
- https://aragon.org/dao
- [DAOStack](https://v1.alchemy.do/)

**Ongoing voting on the DAO Platform:**
Please add your proposals for DAO platform and chain: https://www.notion.so/anonymous-dao/66ed25c128c542eea99a4513d334ad8c?v=f380824557774bd6b3a380dbd9777603 so we can vote.

**Comment by AMelhede** [comment]
Is this about which platform to put the DAO on? If so, which options are you considering?

**Comment by mikepsinn** [comment]
@AMelhede I was thinking about Aragon because they have a Polygon option and ETH gas is prohibitively expensive.  Do you have any other recommendations?

**Comment by AMelhede** [comment]
Got it. I appreciate you sharing that. So, that means we would focus choose Polygon?
I completely agree that we should avoid the dramatically high ETH fees.
I am personally really intrigued about Pulsechain by Richard Heart, which comes out in a few months:
https://pulsechain.com/
