### ISSUE TITLE
Document forking and pull request procedure

### ISSUE THREAD

**Issue by agelesspartners** [cure-dao/docs#215]
Ensure I know how to use the correct forking procedure for efficient open-source collaboration.

**Comment by agelesspartners** [comment]
@mikepsinn Thanks! Could you please share a bit more insight from our previous conversation? In the past, I've cloned many repositories so I'm really used to that workflow. If you could shed a bit more light on this, especially if all the developers will be using the same organizational procedure in this case. Thanks!

**Comment by mikepsinn** [comment]
@agelesspartners 

Hi!

Here's the current documentation but it's not great.
https://github.com/cure-dao/draft-whitepaper/blob/main/how-to/task-management/fork-the-repository.md
https://github.com/cure-dao/draft-whitepaper/tree/main/how-to

I'll update the documentation today and paste the links here.

**Comment by mikepsinn** [comment]
@agelesspartners 
Here are some better instructions:  
https://docs.curedao.org/how-to/contribute-to-docs

Let me know if anything's unclear.
