### ISSUE TITLE
Make developer compensation more clear in presentation

### ISSUE THREAD

**Issue by mikepsinn** [cure-dao/docs#219]
https://github.com/cure-dao/draft-whitepaper/blob/main/assets/cure-dao-powerpoint-presentation.pptx

**Comment by AMelhede** [comment]
Where can we access the presentation, give feedback, and suggest edits, @mikepsinn

**Comment by mikepsinn** [comment]
You can access it here: [https://github.com/cure-dao/draft-whitepaper/blob/main/assets/cure-dao-powerpoint-presentation.pptx](https://github.com/cure-dao/draft-whitepaper/blob/main/assets/cure-dao-powerpoint-presentation.pptx?rgh-link-date=2022-02-16T20%3A00%3A44Z)

You can suggest edits here or in new issues. 

We should probably add the relevant slides to the README of this repo (with context) and it could serve as a temporary litepaper. After that, one could make comments on specific portions in https://app.gitbook.com/home

**Comment by AMelhede** [comment]
Splendid. Thank you, Mike. I notice some really intruding charts and info.

How would this look in practice, and what have the results been with it so far?

**Comment by AMelhede** [comment]
Awesome. Thank you! Has it not been presented to any relevant organizations thus far, or?

**Comment by AMelhede** [comment]
That is amazing. Congratulations on that, Mike!
Such a great sign there already!

**Comment by sajustsmile** [comment]
Just created a pull request for newly updated CureDAO presentation 2.0.
