### ISSUE TITLE
Set up wiki.js or git-wiki to make it easier for people not familiar with git to contribute

### ISSUE THREAD

**Issue by mikepsinn** [cure-dao/docs#24]
I added everything to the repo but it needs some configuration:
http://www.drassil.org/git-wiki/main_page

Other Options:
- Sync Notion to Github - https://github.com/narkdown/narkdown-py
- Sync WikiJS to Github - [docs.requarks.io/storage/git](https://docs.requarks.io/storage/git)

I'm trying to link all the contributions to git commits as we want to quantify contributions so we can reward people proportionally for their work when we get the DAO set up.

Notion and WikiJS are a much easier editing experience for non-coders. However, the commits won't be attributed to the editors as they would if they just edited the files and committed via git.

Example wiki.js: https://wiki.crowdsourcingcures.org/

**Comment by mikepsinn** [comment]
Or should we link wiki.js?

**Comment by ishaanbedi** [comment]
Hi! Can you elaborate a bit more about the issue or feature ?

**Comment by mikepsinn** [comment]
Hi, @ishaanbedi! Thanks for writing!  It's lovely to meet you! 

I'm trying to link all the contributions to git commits as we want to quantify contributions so we can reward people proportionally for their work when we get the DAO set up. 

I've got a wiki.js instance here: https://wiki.crowdsourcingcures.org and it's possible to backup wiki.js to a git repo: https://docs.requarks.io/storage/git

WikiJS is a much easier editing experience for non-coders. However, the commits in the WikiJS backup repo won't be attributed to the editors as they would if they just edited the files directly. 

So I thought git-wiki might be a better solution: http://www.drassil.org/git-wiki/main_page

I guess we could just track contributions from the WikiJS API or database, though. 

What do you think?

BTW, how did you discover the repo and can you tell me about your interest?  Thanks! :D

**Comment by ishaanbedi** [comment]
Hey! I am a newbie to contribution & looking forward to doing some contributions for the first time,  and tbh, I didn't understood much of all these.
If possible, can you guide/instruct me about it?

**Comment by mikepsinn** [comment]
Sure!  Do you want to have a call sometime? https://calendly.com/optomitron

**Comment by ishaanbedi** [comment]
Yeah sure! Thanks!
