### ISSUE TITLE
Document business use cases, marketing strategy, associated costs/revenue projections

### ISSUE THREAD

**Issue by mikepsinn** [cure-dao/docs#243]
# Similar Offerings
- https://www.humanapi.co/
- https://validic.com/
- https://datavant.com/

# Marketing Guide
- https://www.brackenmarketing.com/digital-health-marketing-guide

**Comment by mikepsinn** [comment]
Hey @Taliskermalt @jasonm609609 I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/whitepaper-61d189e356639900120527a0/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by agelesspartners** [comment]
Sounds good - thanks Mike!

**Comment by TaruMathur** [comment]
I can also work on this

**Comment by mikepsinn** [comment]
Thanks, @TaruMathur !  :D  I've got some more initial spreadsheets and documentation that I can find and attach to this issue tomorrow.

**Comment by agelesspartners** [comment]
Thanks @mikepsinn 

I think this will need some careful thought.

For business use cases, is this to expand on how businesses will use the platform / software we're building?

**Comment by mikepsinn** [comment]
Moved to https://app.clickup.com/t/2hbp762.  Let me know if you didn't get the ClickUp invitation.
