### ISSUE TITLE
Write Governance Framework Overview

### ISSUE THREAD

**Issue by mikepsinn** [cure-dao/docs#46]
- [ ] Summary
- [ ] Proposal Process

**Comment by Taliskermalt** [comment]
ADP-1 Draft now written. https://docs.google.com/document/d/1hkl5n7WlG6Nmr-ZvPU_oW7D-EHZ9dSbGoZdt4ttaZwM/edit?usp=sharing

**Comment by mikepsinn** [comment]
@Taliskermalt Thanks for writing this up!  Great work!  Would you like to commit it, or shall I?
